### ISSUE TITLE
cli show usage if no subcommand is provided

### ISSUE THREAD

**Issue by aheinzel** [physion/ovation-python#102]
ovation.cli currently relies on the user to invoke it with either "-h" or a subcommand. After parsing the arguments (and creating a new session) it tries to invoke args.func, unless invoked with -h which is handled by argparse. In case no subcommand is provided the attribute func will not be available causing python to terminate with an error (traceback is shown). As a user I would prefer to see the usage information printed so that I can check how to use ovation.cli. 

current output (paths have been scrubbed):
> ovation-cli.sh 
Traceback (most recent call last):
  File "XXX/python/3.5.0/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "XXX/python/3.5.0/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "XXX/lib/python3.5/site-packages/ovation/cli.py", line 112, in <module>
    result = main()
  File "XXX/lib/python3.5/site-packages/ovation/cli.py", line 108, in main
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

**Comment by barrywark** [comment]
Resolved by https://github.com/physion/ovation-python/pull/105
